name: merch_lints
description: Dart linter rules used by the CHFTM team.
version: 3.0.0
repository: https://github.com/chftm/merch_lints
homepage: https://github.com/chftm/merch_lints
issue_tracker: https://github.com/chftm/merch_lints/issues

topics:
  - lint
  - code-style

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_linter: ^1.1.1
  very_good_analysis: ^5.0.0+1
